### ISSUE TITLE
`...`s in pagination navigation not colapsing when not needed

### ISSUE THREAD

**Issue by Bottersnike** [makegirlsmoe/crypko#6]
This shouldn't really need much more than a picutre to explain it:
![image](https://user-images.githubusercontent.com/7524553/40936518-804fa9f6-6833-11e8-8710-e2b938987a5a.png)

Between the `1` and the `2`. It should colapse down to `1 2 [3] 4 ... 12` instead of `1 ... 2 [3] 4 ... 12`.

**Comment by hanezu** [comment]
This is an issue of Vuetify, the design framework we chose. You can reproduce the same problem on their [demo](https://next.vuetifyjs.com/en/components/paginations#example-long).
Actually, we consider it to be a design choice, since `1 2 [3] 4 ... 12` is composed of 6 elements, which is one less than a normal case, (e.g. `1 ... 2 [3] 4 ... 12` or `1 ... 3 [4] 5 ... 12` is composed of 7 elements). Therefore for `1 2 [3] 4 ... 12` the total width of the pagination will change, which results in the changing of position of the `>` and `<` buttons, so a user has to change the position of the cursor to navigate via these buttons.
We can, of course, choose `1 2 [3] 4 5 ... 12` instead but then it is not symmetric (also a design choice).
